spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/pasila?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update # create / none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 100~1000 권장

logging:
  level:
    org.hibernate.SQL: debug
  file:
    path: logs
#  org.hibernate.type: trace

#chatGpt
openai:
  model: gpt-3.5-turbo
  style-model: ${OPEN_AI_STYLE_MODEL}
  api:
    url: https://api.openai.com/v1
    key: ${OPEN_AI_KEY}

#s3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESSKEY}
      secretKey: ${AWS_SECRETKEY}
    s3:
      bucket: pasila
    region:
      static: ap-northeast-2
    stack:
      auto: false

#server
server:
  port: 80

#swagger
springdoc:
  swagger-ui:
    # swagger-ui 접근 경로. default 값은 /swagger-ui.html이다.
    path: /swagger-pasila-ui.html

    # 각 API의 그룹 표시 순서
    # path, query, body, response 순으로 출력
    groups-order: DESC

    # 태그 정렬 순서.
    # alpha: 알파벳 순 정렬
    # method: OpenAPI specification file에 원하는 태그 정렬 방식 직접 기재
    tags-sorter: alpha

    # 컨트롤러 정렬 순서.
    # method는 delete - get - patch - post - put 순으로 정렬된다.
    # alpha를 사용해 알파벳 순으로 정렬할 수 있다.
    operations-sorter: method

    # swagger-ui default url인 petstore html의 비활성화 설정
    disable-swagger-default-url: true

    # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
    display-request-duration: true

  # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
  api-docs:
    path: /api-docs

  # Spring Actuator의 endpoint까지 보여줄 것인지?
  show-actuator: true

  # request media type 의 기본 값
  default-consumes-media-type: application/json

  # response media type 의 기본 값
  default-produces-media-type: application/json

  # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
  paths-to-match:
    - /api/**

# coolsms
coolsms:
  apiKey: ${COOLSMS_APIKEY}
  apiSecret: ${COOLSMS_APISECRET}
  fromNumber: ${COOLSMS_FROMNUMBER}

# redis
redis:
  host: ${REDIS_URL}
  port: ${REDIS_PORT}

# ffmpeg
ffmpeg:
  url: ${FFMPEG_URL}

# openvidu
openvidu:
  openvidu_url: ${OPENVIDU_URL}
  openvidu_secret: ${OPENVIDU_SECRET}

# google SMTP
mail:
  host: ${MAIL_URL}
  port: ${MAIL_PORT}
  username: ${USER_EMAIL}
  password: ${USER_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        timeout: 5000
#        starttls:
#          enable: true
        ssl:
          enable: true

jwt:
  expiration_time: 86400000
  secret: ${JWT_SECRET}
